### ISSUE TITLE
Compilation error in oflops with Ubuntu 18.04

### ISSUE THREAD

**Issue by tbarbette** [mininet/mininet#876]
util/mininet.sh does not work with Ubuntu 18.04

```
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall -I/home/tom/workspace/mininet/openflow/include -Wshadow `pkg-config --cflags libconfig`  -L/home/tom/workspace/mininet/openflow/lib `pkg-config --libs libconfig` -o liboflops_test.la -rpath /usr/local/lib test_module.lo msgbuf.lo pcap_track.lo oflops_snmp.lo utils.lo wc_event.lo -lnetsnmp
libtool: link: gcc -g -O2 -Wall -I/home/tom/workspace/mininet/openflow/include -Wshadow -Wl,-E -o oflops channel_info.o context.o control.o module_run.o module_default.o oflops.o oflops_pcap.o timer_event.o msg.o log.o traffic_generator.o usage.o  -L/home/tom/workspace/mininet/openflow/lib -lconfig -ldl -lpcap -lnetsnmp -loflops_test -lpthread
/usr/local/bin/ld: cannot find -loflops_test
collect2: error: ld returned 1 exit status
Makefile:576: recipe for target 'oflops' failed
make[2]: *** [oflops] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: link: gcc -shared  -fPIC -DPIC  .libs/test_module.o .libs/msgbuf.o .libs/pcap_track.o .libs/oflops_snmp.o .libs/utils.o .libs/wc_event.o   -L/home/tom/workspace/mininet/openflow/lib -lconfig -lnetsnmp  -g -O2   -Wl,-soname -Wl,liboflops_test.so.0 -o .libs/liboflops_test.so.0.0.0
libtool: link: (cd ".libs" && rm -f "liboflops_test.so.0" && ln -s "liboflops_test.so.0.0.0" "liboflops_test.so.0")
libtool: link: (cd ".libs" && rm -f "liboflops_test.so" && ln -s "liboflops_test.so.0.0.0" "liboflops_test.so")
libtool: link: ar cru .libs/liboflops_test.a  test_module.o msgbuf.o pcap_track.o oflops_snmp.o utils.o wc_event.o
libtool: link: ranlib .libs/liboflops_test.a
libtool: link: ( cd ".libs" && rm -f "liboflops_test.la" && ln -s "../liboflops_test.la" "liboflops_test.la" )
make[2]: Leaving directory '/home/tom/workspace/mininet/oflops'
Makefile:641: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tom/workspace/mininet/oflops'
Makefile:433: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried with master, 2.3.0d5 and 2.2.2

**Comment by kryptur** [comment]
Did you find a solution?

**Comment by svenchen90** [comment]
Do shown below before installing mininet

$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get dist-upgrade

**Comment by crisbermud** [comment]
Installation script isn't working well for me as well. I tried to install Mininet 2.2.2 and 2.3.0d5 on Ubuntu 20.04.1 but cbench component always failed with the following error related to liboflops.

`/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall -I/opt/mininet/openflow/include -Wshadow `pkg-config --cflags libconfig` -static -Wl,-E -L/opt/mininet/openflow/lib `pkg-config --libs libconfig` -o oflops channel_info.o context.o control.o module_run.o module_default.o oflops.o oflops_pcap.o timer_event.o msg.o log.o traffic_generator.o usage.o -ldl -lpcap -lnetsnmp -loflops_test -lpthread 
libtool: link: gcc -g -O2 -Wall -I/opt/mininet/openflow/include -Wshadow -Wl,-E -o oflops channel_info.o context.o control.o module_run.o module_default.o oflops.o oflops_pcap.o timer_event.o msg.o log.o traffic_generator.o usage.o  -L/opt/mininet/openflow/lib -lconfig -ldl -lpcap -lnetsnmp -loflops_test -lpthread
/usr/bin/ld: cannot find -loflops_test
collect2: error: ld returned 1 exit status
`
I couldn't fix the error so just skip installing it...

**Comment by ishitachaturvedi** [comment]
I am facing the same issue, was it resolved?

**Comment by lantz** [comment]
Tested and working in 2.3.0b2.

**Comment by tobiayofe** [comment]
I'm experiencing this same issue please. I'm using mininet version 2.6.

**Comment by lantz** [comment]
2.6?

**Comment by tbarbette** [comment]
With the latest version, 2.3.1b1, the problem is fixed with 20.04 LTS for me at least :)

**Comment by tobiayofe** [comment]
> With the latest version, 2.3.1b1, the problem is fixed with 20.04 LTS for me at least :)

Well I'm using an Ubuntu variant called Lubuntu and it's Ubuntu 20.04 LTS. I ran the command below:
"sh ./boot.sh ; ./configure --with-openflow-src-dir=~/oflops/openflow/; sudo make" OR
sh ./boot.sh ; ./configure --with-openflow-src-dir=~/oflops/openflow/; make"

Both of them results in the images below:

![image](https://user-images.githubusercontent.com/43920326/202872654-81553c65-229c-43c2-ad17-bfa3701e36be.png)

![image](https://user-images.githubusercontent.com/43920326/202872684-3d5b649d-37f4-4c5b-861b-1ae43ab5d9b6.png)

**Comment by tbarbette** [comment]
I just used the OS package for openflow.

**Comment by tobiayofe** [comment]
> I just used the OS package for openflow.

So you don't use Cbench or other performance benchmarking tool on it?

**Comment by tbarbette** [comment]
Not sure what you're referring to. I'm the OP of this issue. A few years ago I could not compile mininet on Ubuntu 18.04. And with time it was fixed. Nothing really related to openflow here.

**Comment by tobiayofe** [comment]
> Not sure what you're referring to. I'm the OP of this issue. A few years ago I could not compile mininet on Ubuntu 18.04. And with time it was fixed. Nothing really related to ovs here.

Well, my complaints here wasn't about openflow or mininet from the on set. I was complaining about an error due to Cbench installation on a mininet VM instance.

**Comment by tobiayofe** [comment]
> > Not sure what you're referring to. I'm the OP of this issue. A few years ago I could not compile mininet on Ubuntu 18.04. And with time it was fixed. Nothing really related to ovs here.
> 
> Well, my complaints here wasn't about openflow or mininet from the on set. I was complaining about an error due to Cbench installation on a mininet VM instance.

Perhaps, I have made complaints in the wrong box. I thought seeing oflops was about Cbench which is the main directory for the Cbench cloned to the mininet VM.
